apiVersion: v1
kind: Service
metadata:
  name: midproject_app-service
spec:
  type: LoadBalancer
  selector:
    app: midproject_app 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
